version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    secrets:
      - db_password

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    secrets:
      - db_password
      - db_root_password

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
